site_name: Basic Programming
nav:
  - صفحه اصلی: index.md
  - درسنامه:
    - content/index.md
    - Compiler and environment: content/Compiler_and_env.md
    - Hello World: content/helloWorld.md
  - تمرین ها:
    - blog/index.md

theme:
  name: material
  direction: rtl
  logo: assets/University_of_Tehran_logo.svg.png
  favicon: assets/University_of_Tehran_logo.svg.png
  language: fa
  features: 
    - content.code.copy
    - content.code.annotate
    - navigation.footer
    - navigation.indexes
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - navigation.expand
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  palette:
    - scheme: slate
      primary: teal
      toggle:
        icon: material/brightness-7
        name: switch to dark mode

    - scheme: default
      primary: cyan
      toggle:
        icon: material/brightness-4
        name: salam

  font:
    text: Vazirmatn
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - admonition
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
plugins:
  - search
  - blog
  - tags
